/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package source;

import org.junit.Test;
import static org.junit.Assert.*;

public class CalculatorTest {
    @Test public void calculatorCanAdd() {
        Calculator classUnderTest = new Calculator();
        assertEquals(10, classUnderTest.addition(5,5));
    }

    @Test public void calculatorCanMultiplyBy2() {
        Calculator classUnderTest = new Calculator();
        assertEquals(10, classUnderTest.multiplyBy2(4));
    }
}
